server:
  port: 8082 # Đổi sang 8082 để tránh trùng cổng mạng của máy nhé bro

spring:
  application:
    name: flashcardkorean

  # Cấu hình kết nối MySQL thực tế theo Workbench của bạn
  datasource:
    url: jdbc:mysql://localhost:3306/flashcard_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # Cơ chế tự động đồng bộ hóa Entities code Java với Database MySQL
    hibernate:
      ddl-auto: update
    
    # Kích hoạt log để theo dõi câu lệnh SQL chạy dưới Console
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect